[package]
name = "pcb"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
config.workspace = true
itoa.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
