[package]
name = "model"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
config.workspace = true
earcutr.workspace = true
glam.workspace = true
fidget.workspace = true

[lints]
workspace = true
