[package]
name = "concavum-customizer"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6.2", default-features = false }
fj-interop = "0.47.0"
fj-math = "0.47.0"
fj-viewer = "0.47.0"
futures = "0.3.28"
glam = { version = "0.23", features = ["serde"] }
hex_color = { version = "2.0.0", features = ["serde"] }
notify = "6.0.1"
opencascade = { git = "https://github.com/julianschuler/opencascade-rs", branch = "surface", version = "0.1.0" }
opencascade-sys = { git = "https://github.com/julianschuler/opencascade-rs", branch = "surface", version = "0.1.0" }
serde = { version = "1.0.174", features = ["derive"] }
thiserror = "1.0.43"
toml = "0.7.6"
winit = "0.28.6"
