[package]
name = "concavum-customizer"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = { version = "0.6", default-features = false }
earcutr = "0.4.3"
fidget = { git = "https://github.com/julianschuler/fidget.git", branch = "static-singular-value-truncation", default-features = false, features = ["jit", "mesh"] }
futures = "0.3"
glam = { version = "0.27", features = ["serde"] }
hex_color = { version = "3.0", features = ["serde"] }
notify = "6.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
three-d = { version = "0.17", features = ["egui-gui"] }
toml = "0.8"
winit = "0.28"
