[package]
name = "concavum-customizer"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.102"
fj-interop = "0.47.0"
fj-math = "0.47.0"
fj-viewer = "0.47.0"
futures = "0.3.28"
notify = "6.0.1"
opencascade-sys = { git = "https://github.com/bschwind/opencascade-rs", version = "0.1.0" }
serde = { version = "1.0.174", features = ["derive"] }
thiserror = "1.0.43"
toml = "0.7.6"
winit = "0.28.6"
