points1 = [
  [0.0, 1.0, 0.0], [0.5, 1.0, 0.0], [0.5, 1.0, 0.5], [1.0, 1.0, 0.5]
]
points2 = [
  [0.0, 0.0, 0.0], [0.5, 0.0, 0.0], [0.5, 0.0, 1.0], [1.0, 0.0, 0.5]
]


[preview]
# Show the keys during preview
show_keys = true
# Show the interface PCB during preview
show_interface_pcb = true
# Show the bottom plate during preview
show_bottom_plate = true


[finger_cluster]
# Amount of rows, automatic PCB generation is supported for 1 to 5 rows
rows = 3
# Settings per column, automatic PCB generation is supported for 2 to 6 columns
columns = [
  # Finger column curvature as angle between two neighbouring keys and offset along Y and Z
  { curvature_angle = 20, offset = [0, 0] },
  { curvature_angle = 20, offset = [0, 0] },
  { curvature_angle = 20, offset = [0, -3] },
  { curvature_angle = 20, offset = [0, 0] },
  { curvature_angle = 20, offset = [-20, 5] },
  { curvature_angle = 20, offset = [-20, 5] },
]
# Finger column side rotation angles for the left- and rightmost columns
side_angles = [15, 15]


[thumb_cluster]
# Amount of thumb keys, automatic PCB generation is supported for 1 to 6 keys
keys = 3
# Thumb well curvature as angle between two neighbouring keys
curvature = 15
# Rotation of the thumb cluster in relation to the finger cluster
rotation = [30, 15, 80]
# Offset of the thumb cluster in relation to the finger cluster
offset = [-3.05, -48, 10]


[keyboard]
# Keyboard tilting angle along X and Y
tilting_angle = [15, 20]
# Thickness of the keyboard shell
shell_thickness = 2.1
# Thickness of the bottom plate
bottom_plate_thickness = 1.6


[colors]
keycap = "#333333"
switch = "#E6E6E6"
matrix_pcb = "#008C4A"
interface_pcb = "#6C0D5D"
fpc_connector = "#8F8F8F"
