[preview]
# Show the keys during preview
show_keys = true
# Show the interface PCB during preview
show_interface_pcb = true
# Show the bottom plate during preview
show_bottom_plate = true
# Triangulation tolerance, lower values result in higher preview fidelity
triangulation_tolerance = 0.1
# Light directions, will be hardcoded at a later stage
light_directions = [[0.0, -0.6, 0.1]]

[finger_cluster]
# Amount of rows, automatic PCB generation is supported for 1 to 5 rows
rows = 3
# Settings per column, automatic PCB generation is supported for 2 to 6 columns
columns = [
  # Finger column curvature as angle between two neighbouring keys and offset along Y and Z
  { curvature_angle = 20, offset = [0, 0] },
  { curvature_angle = 20, offset = [0, 0] },
  { curvature_angle = 20, offset = [0, -3] },
  { curvature_angle = 20, offset = [0, 0] },
  { curvature_angle = 20, offset = [-20, 5] },
  { curvature_angle = 20, offset = [-20, 5] },
]
# Finger column side rotation angles for the left- and rightmost columns
side_angles = [15, 15]
# Distance between two neighbouring keys in X and Y direction
key_distance = [19.05, 19.05]
# Row index of the home row (usually 1)
home_row_index = 1


[thumb_cluster]
# Amount of thumb keys, automatic PCB generation is supported for 1 to 6 keys
keys = 3
# Thumb well curvature as angle between two neighbouring keys
curvature_angle = 15
# Rotation of the thumb cluster in relation to the finger cluster
rotation = [30, 15, 80]
# Offset of the thumb cluster in relation to the finger cluster
offset = [-3.05, -48, 10]
# Distance between two neighbouring keys
key_distance = 19.05

[keyboard]
# Keyboard tilting angle along X and Y
tilting_angle = [15, 20]
# Thickness of the keyboard shell
shell_thickness = 2.1
# Thickness of the bottom plate
bottom_plate_thickness = 1.6


[colors]
keycap = "#0F0F0F"
switch = "#FFFFFF"
matrix_pcb = "#008C4A"
interface_pcb = "#6C0D5D"
fpc_connector = "#8F8F8F"
background = "#282828"
